name: Auto-label issues as "bug"

on:
  issues:
    types: [opened]

jobs:
  label_bug:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "bug" in issue title or body
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body.toLowerCase();
            if (title.includes("bug") || body.includes("bug")) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["bug"]
              });
              console.log("Added 'bug' label to issue.");
            } else {
              console.log("No 'bug' keyword found.");
            }
