name: Test Project
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch 
        uses: actions/checkout@v3

      - name: List files
        run: ls -al
